[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "adapter"
version = "1.0.7"
dependencies = [
    "logger @ git+https://github.com/Goldkugel/logger.git@v1.0.6"
]

[tool.setuptools]
packages = [
    "adapter",
    "adapter.hpo",
    "adapter.sct",
    "adapter.umls"
]

[tool.setuptools]
py-modules = ["Embedder", "EmbedderConfig"]